/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication43;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import model.ConnectionBuilder;
import model.Function;

/**
 *
 * @author Bestiiz
 */
public class Review extends javax.swing.JFrame {

    /**
     * Creates new form Review
     */
    private int orderdetail_id=0;
    private String username="";
    private int orid=0;
    public Review() {
        initComponents();
    }
    public Review(String user,int id) {
        initComponents();
        username = user;
        orid = id;
    }
    public Review(String user,int id,int ordtid) {
        initComponents();
        username = user;
        orid = id;
        orderdetail_id=ordtid;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        productname = new javax.swing.JTextField();
        orderdetailid = new javax.swing.JTextField();
        radio5 = new javax.swing.JRadioButton();
        radio1 = new javax.swing.JRadioButton();
        radio2 = new javax.swing.JRadioButton();
        radio3 = new javax.swing.JRadioButton();
        radio4 = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        comment = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 102, 102));
        jPanel1.setPreferredSize(new java.awt.Dimension(526, 301));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB", 0, 36)); // NOI18N
        jLabel3.setText("REVIEW");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 150, 46));

        jLabel6.setFont(new java.awt.Font("Berlin Sans FB", 0, 19)); // NOI18N
        jLabel6.setText("ODER DETAIL ID :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, -1, -1));

        jLabel10.setFont(new java.awt.Font("Berlin Sans FB", 0, 19)); // NOI18N
        jLabel10.setText("PRODUCT NAME :");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, -1, -1));

        jLabel8.setFont(new java.awt.Font("Berlin Sans FB", 0, 19)); // NOI18N
        jLabel8.setText("COMMENT : ");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, -1, -1));

        jLabel9.setFont(new java.awt.Font("Berlin Sans FB", 0, 19)); // NOI18N
        jLabel9.setText("RAVIEW RATING : ");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, -1, -1));
        jPanel1.add(productname, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 240, -1));
        jPanel1.add(orderdetailid, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 150, -1));

        radio5.setText("5");
        radio5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio5ActionPerformed(evt);
            }
        });
        jPanel1.add(radio5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 290, -1, -1));

        radio1.setText("1");
        radio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio1ActionPerformed(evt);
            }
        });
        jPanel1.add(radio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, -1, -1));

        radio2.setText("2");
        radio2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio2ActionPerformed(evt);
            }
        });
        jPanel1.add(radio2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, -1, -1));

        radio3.setText("3");
        radio3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio3ActionPerformed(evt);
            }
        });
        jPanel1.add(radio3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 290, -1, -1));

        radio4.setText("4");
        radio4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio4ActionPerformed(evt);
            }
        });
        jPanel1.add(radio4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 290, -1, -1));

        comment.setColumns(20);
        comment.setLineWrap(true);
        comment.setRows(5);
        jScrollPane1.setViewportView(comment);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 370, -1));

        jButton1.setText("SUBMIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 520, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 786, 585));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int rating=0;
        if(radio1.isSelected() == true && radio2.isSelected() == false && radio3.isSelected() == false && radio4.isSelected() == false && radio5.isSelected() == false){
            rating=1;
        }else if(radio2.isSelected() == true && radio1.isSelected() == false && radio3.isSelected() == false && radio4.isSelected() == false && radio5.isSelected() == false){
            rating=2;
        }
        else if(radio3.isSelected() == true && radio1.isSelected() == false && radio1.isSelected() == false && radio4.isSelected() == false && radio5.isSelected() == false){
            rating=3;
        }
        else if(radio4.isSelected() == true && radio1.isSelected() == false && radio3.isSelected() == false && radio1.isSelected() == false && radio5.isSelected() == false){
            rating=4;
        }
        else if(radio5.isSelected() == true && radio1.isSelected() == false && radio3.isSelected() == false && radio4.isSelected() == false && radio1.isSelected() == false){
            rating=5;
        }
        
        Function func = new Function();
        func.addReview(orderdetail_id,rating,comment.getText());
        
        DetailbyHistory online = new DetailbyHistory(username,orid);
        setVisible(false);
        online.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        try {
            Connection conn = ConnectionBuilder.getConnection();
            String sqlCmd = "select p.prodname from order_detail od JOIN product p ON od.prodId = p.prodId where od.order_detailID = ? ";
            PreparedStatement pstm = conn.prepareStatement(sqlCmd);
            pstm.setInt(1, orderdetail_id);
            ResultSet rs = pstm.executeQuery();
      
            if (rs.next()) {
                orderdetailid.setText(orderdetail_id+"");
                productname.setText(rs.getString("prodname"));                        
            }

            conn.close();
            
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_formComponentShown

    private void radio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio1ActionPerformed
        // TODO add your handling code here:
        radio2.setSelected(false); 
        radio3.setSelected(false); 
        radio4.setSelected(false); 
        radio5.setSelected(false); 
    }//GEN-LAST:event_radio1ActionPerformed

    private void radio2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio2ActionPerformed
        // TODO add your handling code here:
        radio1.setSelected(false); 
        radio3.setSelected(false); 
        radio4.setSelected(false); 
        radio5.setSelected(false); 
    }//GEN-LAST:event_radio2ActionPerformed

    private void radio3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio3ActionPerformed
        // TODO add your handling code here:
        radio2.setSelected(false); 
        radio1.setSelected(false); 
        radio4.setSelected(false); 
        radio5.setSelected(false); 
    }//GEN-LAST:event_radio3ActionPerformed

    private void radio4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio4ActionPerformed
        // TODO add your handling code here:
        radio2.setSelected(false); 
        radio3.setSelected(false); 
        radio1.setSelected(false); 
        radio5.setSelected(false); 
    }//GEN-LAST:event_radio4ActionPerformed

    private void radio5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio5ActionPerformed
        // TODO add your handling code here:
        radio2.setSelected(false); 
        radio3.setSelected(false); 
        radio4.setSelected(false); 
        radio1.setSelected(false); 
    }//GEN-LAST:event_radio5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Review.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Review.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Review.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Review.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Review().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea comment;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField orderdetailid;
    private javax.swing.JTextField productname;
    private javax.swing.JRadioButton radio1;
    private javax.swing.JRadioButton radio2;
    private javax.swing.JRadioButton radio3;
    private javax.swing.JRadioButton radio4;
    private javax.swing.JRadioButton radio5;
    // End of variables declaration//GEN-END:variables
}
